In [1]:
import numpy as np
import pandas as pd
import os
import warnings
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
path='C:\\Users\\User\\Documents\\Zomato Restaurant Project'
dataset=pd.read_csv(os.path.join(path,'zomato.csv'),encoding='latin-1')

In [3]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   str
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   str
 4   Address               9551 non-null   str
 5   Locality              9551 non-null   str
 6   Locality Verbose      9551 non-null   str
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   str
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   str
 12  Has Table booking     9551 non-null   str
 13  Has Online delivery   9551 non-null   str
 14  Is delivering now     9551 non-null   str
 15  Switch to order menu  9551 non-null   str
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   str
 19  Rating text           9551 non-null   str
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), str(13)
memory usage: 1.5 MB

In [4]:
country_df=pd.read_excel(os.path.join(path,'Country-Code.xlsx'))

In [5]:
final_dataset=dataset.merge(country_df,on='Country Code',how='left')
columns=['Country Code','Locality Verbose','Is delivering now','Switch to order menu','Rating color','Currency']
final_dataset.drop(columns=columns,inplace=True)
final_dataset=final_dataset[final_dataset['Country']=='India']

In [17]:
final_dataset.iloc[0]['Restaurant ID']

np.int64(3400025)

In [6]:
final_dataset.columns

Index(['Restaurant ID', 'Restaurant Name', 'City', 'Address', 'Locality',
       'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Has Online delivery', 'Price range',
       'Aggregate rating', 'Rating text', 'Votes', 'Country'],
      dtype='str')

In [221]:
column=['Restaurant Name','Cuisines','Locality','City','Has Table booking','Has Online delivery','Average Cost for two','Aggregate rating']
final_dataset[column]

,Restaurant Name,Cuisines,Locality,City,Has Table booking,Has Online delivery,Average Cost for two,Aggregate rating
624,Jahanpanah,"North Indian, Mughlai",Agra Cantt,Agra,No,No,850,3.9
625,Rangrezz Restaurant,"North Indian, Mughlai",Agra Cantt,Agra,No,No,700,3.5
626,Time2Eat - Mama Chicken,North Indian,Agra Cantt,Agra,No,No,500,3.6
627,Chokho Jeeman Marwari Jain Bhojanalya,Rajasthani,Civil Lines,Agra,No,No,400,4.0
628,Pinch Of Spice,"North Indian, Chinese, Mughlai",Civil Lines,Agra,No,No,1000,4.2
...,...,...,...,...,...,...,...,...
9271,D Cabana,"Continental, Seafood, Chinese, North Indian, B...",Sagar Nagar,Vizag,No,No,600,3.6
9272,Kaloreez,"Cafe, North Indian, Chinese",Siripuram,Vizag,No,No,400,3.7
9273,Plot 17,"Burger, Pizza, Biryani",Siripuram,Vizag,No,No,600,4.3
9274,Vista - The Park,"American, North Indian, Thai, Continental","The Park, Lawsons Bay",Vizag,No,No,1500,3.8
9275,Flying Spaghetti Monster,Italian,Waltair Uplands,Vizag,No,No,1400,4.4

In [88]:
final_dataset['Cuisines']=final_dataset['Cuisines'].str.split(",").apply(lambda x:[i.strip() for i in x])
final_dataset['Cuisines']=final_dataset['Cuisines'].apply(lambda x: [i.replace(" ","_") for i in x])
final_dataset['Cuisines']=final_dataset['Cuisines'].apply(lambda x : ' '.join(x))

In [98]:
final_dataset.Cuisines.sample(5)

2987      North_Indian Street_Food Mithai
5261                     Bakery Fast_Food
6526                                 Cafe
6469    Chinese North_Indian South_Indian
7366                                 Cafe
Name: Cuisines, dtype: str

<h1> Cases:</h1>
<ol>
    <li>show top 10 similar restaurants to the one user selected based on cuisines filter by city.
    <li>conditions:locality is given by user,top 10 similar restaurants in locality by cuisines.
    <li>conditions: minimum rating given
        <ul>
            <li>price range is not given-->sort them from primium to cheap</li>
            <li>price range is given-->filter by price range and then sort them in desc</li>
        </ul></li>
    <li>conditions: when ratings,price range,table booking,online delivery -->re rank them based on condition</li>
</ol>

In [101]:
tfidf= TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,1),
    lowercase=True
)
tfidf_matrix=tfidf.fit_transform(final_dataset['Cuisines'])
similarity_matrix=cosine_similarity(tfidf_matrix,tfidf_matrix)

In [190]:
restaurant_index=pd.Series(final_dataset.index-624,index=final_dataset['Restaurant Name'])

def recommendation_func(restaurant_name,restaurant_index,n):
    idx=restaurant_index[restaurant_name]
    scores=list(enumerate(similarity_matrix[idx]))
    sorted_scores=sorted(scores,key=lambda x:x[1],reverse=True)
    sim_scores=sorted_scores[1:n]
    restaurant_indices=[i[0] for i in sim_scores]
    recommend=final_dataset.iloc[restaurant_indices].copy()
    recommend['similarity_score']=[i[1] for i in sim_scores]
    return recommend

In [182]:
final_dataset.loc[final_dataset['Restaurant Name']=="Subway"].tail()

,Restaurant ID,Restaurant Name,City,Address,Locality,Longitude,Latitude,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Price range,Aggregate rating,Rating text,Votes,Country
8736,3707,Subway,Noida,"B-1/24, Central Market, Near City Centre Metro...",Sector 50,77.361918,28.570513,American Fast_Food Salad Healthy_Food,500,No,No,2,2.5,Average,165,India
8884,308758,Subway,Noida,"A-44-45, Galaxy IT Park, Sector 62, Noida",Sector 62,77.370417,28.624539,American Fast_Food Salad Healthy_Food,500,No,Yes,2,2.5,Average,28,India
8923,7909,Subway,Noida,"C Block, Logic Cyber Park, Sector 62, Noida",Sector 62,77.366493,28.612903,American Fast_Food Salad Healthy_Food,500,No,Yes,2,2.4,Poor,88,India
9041,4482,Subway,Noida,"Food Court, 2nd Floor, Spice World Mall, Secto...","Spice World Mall, Sector 25",77.339801,28.586405,American Fast_Food Salad Healthy_Food,500,No,Yes,2,3.4,Average,93,India
9070,18070483,Subway,Noida,"Shop 3, Supertech Shopprix Mall, Sector 61, Noida","Supertech Shopprix Mall, Sector 61",77.364981,28.596898,American Fast_Food Salad Healthy_Food,500,No,Yes,2,2.3,Poor,24,India

In [191]:
recommendation=recommendation_func("Subway",restaurant_index,5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [187]:
recommendation.head()

,Restaurant ID,Restaurant Name,City,Address,Locality,Longitude,Latitude,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Price range,Aggregate rating,Rating text,Votes,Country,similarity_score
1240,313149,Smaaash,Gurgaon,"Cyber Hub, DLF Cyber City, Gurgaon","Cyber Hub, DLF Cyber City",77.088913,28.495005,North_Indian Thai Continental,1400,No,No,3,3.9,Good,622,India,0.797645
8074,18303688,Smaaash,Noida,"4th Floor, DLF Mall of India, Sector 18, Noida","DLF Mall of India, Sector 18, Noida",77.320824,28.567330,North_Indian Thai Continental,1350,No,No,3,4.0,Very Good,121,India,0.797645
6769,18382353,DEL - Roseate House,New Delhi,"Roseate House, Asset 10, Hospitality District,...","Roseate House, Aerocity",77.120533,28.550802,Continental American North_Indian,3000,Yes,No,4,3.6,Good,30,India,0.788404
738,18385443,Koramangala Social,Bangalore,"118, Koramangala Industrial Area, Koramangala ...",Koramangala 7th Block,77.614130,12.935662,Continental American,1500,No,No,3,4.5,Excellent,1288,India,0.753570

In [188]:
recommendation2=recommendation("Subway",restaurant_index,5)
recommendation2.head()

TypeError: 'DataFrame' object is not callable

In [ ]:
def name_to_id(restaurant_name):
    if restaurant_name not in dataset:
        return f"Restaurant is not available."
    elif (dataset['restaurant_name']==restaurant_name) & (dataset['has_branch']==1)]:
        call a function for showing all the restaurant with name == restaurant_name
    else:
        id=dataset[dataset['restaurant_name']==restaurant_name]['restaurant id']
    return id

In [200]:
def showing_restaurant(restaurant_name):
    return dataset[dataset['restaurant name']==restaurant_name]

In [21]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   str
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   str
 4   Address               9551 non-null   str
 5   Locality              9551 non-null   str
 6   Locality Verbose      9551 non-null   str
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   str
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   str
 12  Has Table booking     9551 non-null   str
 13  Has Online delivery   9551 non-null   str
 14  Is delivering now     9551 non-null   str
 15  Switch to order menu  9551 non-null   str
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   str
 19  Rating text           9551 non-null   str
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), str(13)
memory usage: 1.5 MB

In [46]:
def preprocess(path,code_path):
    df=pd.read_csv(path,encoding='latin-1')
    country_df=pd.read_excel(code_path)
    merge_df=df.merge(country_df,on='Country Code',how='left')
    merge_df.drop(columns=['Country Code','Is delivering now','Switch to order menu','Rating color','Locality Verbose','Currency'],inplace=True)
    merge_df.dropna(axis=0,inplace=True)
    merge_df.drop_duplicates(inplace=True)
    merge_df=merge_df.loc[merge_df['Country']=='India']
    merge_df.to_csv("final_dataset.csv")

In [81]:
class Recommendation_System():
    def __init__(self):
        self.sim_matrix=None
        self.dataset=None
        self.tfidf_matrix=None
        self.index=None
        
    def load_data(self,file_path):
        dataset_path=file_path
        df=pd.read_csv(dataset_path,encoding='latin-1')
        df['Cuisines']=df['Cuisines'].str.split(',').apply(lambda x: [val.strip().replace(" ","_") for val in x])
        df['Cuisines_processed']=df['Cuisines'].apply(lambda x: " ".join(x))
        
        df['Combined_col']=(
            df['Restaurant Name'].str.lower()+" "+
            df['City'].str.lower()+" "+
            df['Locality'].str.lower()+" "+
            df['Cuisines_processed'].str.lower()
        )
        if "Unnamed: 0" in df.columns:
            df.drop(columns=['Unnamed: 0'],inplace=True)
        self.dataset=df
        print(f'Successfully loaded and process the dataset {self.dataset.shape}')
        return self.dataset.head()

    def model_develop(self):
        if self.dataset is None:
            raise ValueError("Load the data first using the load_data().")
        df=self.dataset
        tfidf=TfidfVectorizer(
            max_features=5000,
            ngram_range=(1,2),
            lowercase=True,
            stop_words='english'
        )
        vectors=tfidf.fit_transform(df['Combined_col'])
        similarity_matrix=cosine_similarity(vectors,vectors)
        
        restaurant_idx=dict(zip(df['Restaurant ID'],df.index))
        self.sim_matrix=similarity_matrix
        self.index=restaurant_idx
        self.tfidf_matrix=vectors
        print(f"model successfully build, {similarity_matrix.shape}")

    def name_to_id(self,Restaurant_name,city_hint=False):
        match=self.dataset[self.dataset['Restaurant Name'].str.lower()==Restaurant_name.lower()]
        if match.empty:
            return None
        if len(match)==1:
            return match.iloc[0]['Restaurant ID']
        if city_hint:
            match=match[match['City'].str.lower().str.contains(city_hint.lower())]
            if len(match)==1:
                return match.iloc[0]['Restaurant ID']
            if len(match)==0:
                return None
        match=match.sort_values(by=['Aggregate rating','Votes'],ascending=[False,False])
        print(f"Multiple branches exists for restaurant {Restaurant_name}. Selected the highest rated one.")
        self.print_restaurant_branch(match.head(5))
        return match.iloc[0]['Restaurant ID']
            
        
    def print_restaurant_branch(self,restaurant_branch):
        columns=['Restaurant Name','Cuisines_processed','Locality','City','Has Table booking','Has Online delivery','Average Cost for two','Aggregate rating']
        print(f'Printing the top 5 Branches for the restaurant {restaurant_branch.iloc[0]['Restaurant Name']}')
        print(restaurant_branch[columns].to_string(index=False))
        print("=="*100)

    def get_recommendation(self,name,n,city):
        result=self.name_to_id(name,city)
        if result is None:
            return f"Restaurant{name} not available."
        
        rest_idx=self.index[result]
        score=list(enumerate(self.sim_matrix[rest_idx]))
        sort_score=sorted(score,key=lambda x:x[1],reverse=True)
        
        top_n=sort_score[1:n+1]
        top_index=[i[0] for i in top_n]
        
        recommend=self.dataset.iloc[top_index].copy()
        recommend['similarity_score']=[i[1] for i in top_n]
        return recommend[['Restaurant Name', 'City', 'Locality', 'Cuisines_processed', 
                          'Aggregate rating', 'Votes', 'similarity_score']]
    
    def recommendation_by_cuisines(
        self,
        preferred_cuisines,
        n_recommendations,
        min_rating=None,
        city=None,
        preferred_restaurant=None
    ):
        user_cuisines=[cuisine.strip().replace(' ','_').lower() for cuisine in preferred_cuisines]
        def Has_preferred_cuisine(row):
            if pd.isna(row['Cuisines_processed']):
                print('Cuisines is not available.')
                return False
            restaurant_cuisine=[c.lower().strip() for c in row['Cuisines_processed'].split(',')]
            return any(p in restaurant_cuisine for p in user_cuisines)
        filtered_data=self.dataset[self.dataset.apply(Has_preferred_cuisine,axis=1)].copy()
        if city:
            filtered_data=filtered_data[filtered_data["City"].str.lower().str.strip().str.contains(city.lower())]
        filtered_data=filtered_data[filtered_data['Aggregate rating']>=min_rating]

        if filtered_data.shape[0]==0:
            print('No Restaurants are available')
            return pd.DataFrame()
        
        if preferred_restaurant:
            ref_name=preferred_restaurant.lower()
            if ref_name not in self.dataset['Restaurant Name'].str.lower().tolist():
                print('Restaurant Not Available.')
                return pd.DataFrame()
            else:
                rest_id=self.name_to_id(ref_name,city)
                idx=self.index[rest_id]
                sim_score=self.sim_matrix[idx]
                filter_indice=filtered_data.index
                filtered_sim_score=sim_score[filter_indice]
                sorted_idx = np.argsort(filtered_sim_score)[::-1]
                top_indices = filter_indice[sorted_idx][:n_recommendations]
                
                result = filtered_data.loc[top_indices].copy()
                result['similarity_score'] = filtered_sim_score[sorted_idx][:n_recommendations]
        else:
            result=filtered_data.sort_values(by=['Votes','Aggregate rating'],ascending=[False,False])[:n_recommendations]
            columns=['Restaurant Name', 'City', 'Cuisines', 'Aggregate rating', 'Votes', 'Price range']
            if 'similarity_score' in result.columns:
                columns.append('similarity_score')
            return result[columns].reset_index(drop=True)

In [82]:
path='C:\\Users\\User\\Documents\\Zomato Restaurant Project'
# preprocess(os.path.join(path,'zomato.csv'),os.path.join(path,'Country-Code.xlsx'))

In [83]:
rs = Recommendation_System()
rs.load_data(os.path.join(path,'final_dataset.csv'))
rs.model_develop()

# # Simple similarity
# print(rs.get_recommendation("Domino's Pizza", n=6, city="New Delhi"))

# # Cuisine filtered
recs = rs.recommendation_by_cuisines(
    preferred_cuisines=["South Indian", "Kerala"],
    n_recommendations=5,
    min_rating=4.0,
    city="Delhi",
    preferred_restaurant="Saravana Bhavan"
)
print(recs)

Successfully loaded and process the dataset (8652, 18)
model successfully build, (8652, 8652)
Multiple branches exists for restaurant saravana bhavan. Selected the highest rated one.
Printing the top 5 Branches for the restaurant Saravana Bhavan
Restaurant Name Cuisines_processed                    Locality      City Has Table booking Has Online delivery  Average Cost for two  Aggregate rating
Saravana Bhavan       South_Indian             Connaught Place New Delhi                No                 Yes                   500               4.3
Saravana Bhavan       South_Indian                     Janpath New Delhi                No                 Yes                   500               4.2
Saravana Bhavan       South_Indian Select Citywalk Mall, Saket New Delhi                No                  No                   500               3.9
========================================================================================================================================================================================================
None

In [56]:
df=pd.read_csv(os.path.join(path,'final_dataset.csv'))
print("Saravana Bhavan".lower().strip() in df['Restaurant Name'].str.lower().str.strip())

False

In [16]:
obj=Recommendation_System()

In [17]:
obj.load_data(os.path.join(path,'final_dataset.csv'))

   Unnamed: 0  Restaurant ID                        Restaurant Name  City  \
0         624        3400025                             Jahanpanah  Agra
1         625        3400341                    Rangrezz Restaurant  Agra
2         626        3400005                Time2Eat - Mama Chicken  Agra
3         627        3400021  Chokho Jeeman Marwari Jain Bhojanalya  Agra
4         628        3400017                         Pinch Of Spice  Agra

                                             Address     Locality  Longitude  \
0  E 23, Shopping Arcade, Sadar Bazaar, Agra Cant...   Agra Cantt  78.011544
1  E-20, Shopping Arcade, Sadar Bazaar, Agra Cant...   Agra Cantt   0.000000
2        Main Market, Sadar Bazaar, Agra Cantt, Agra   Agra Cantt  78.011608
3  1/48, Delhi Gate, Station Road, Raja Mandi, Ci...  Civil Lines  77.998092
4  23/453, Opposite Sanjay Cinema, Wazipura Road,...  Civil Lines  78.007553

    Latitude                          Cuisines  Average Cost for two  \
0  27.161661           [North_Indian, Mughlai]                   850
1   0.000000           [North_Indian, Mughlai]                   700
2  27.160832                    [North_Indian]                   500
3  27.195928                      [Rajasthani]                   400
4  27.201725  [North_Indian, Chinese, Mughlai]                  1000

  Has Table booking Has Online delivery  Price range  Aggregate rating  \
0                No                  No            3               3.9
1                No                  No            2               3.5
2                No                  No            2               3.6
3                No                  No            2               4.0
4                No                  No            3               4.2

  Rating text  Votes Country            Cuisines_processed  \
0        Good    140   India          North_Indian Mughlai
1        Good     71   India          North_Indian Mughlai
2        Good     94   India                  North_Indian
3   Very Good     87   India                    Rajasthani
4   Very Good    177   India  North_Indian Chinese Mughlai

                                        Combined_col
0    jahanpanah agra agra cantt north_indian mughlai
1  rangrezz restaurant agra agra cantt north_indi...
2  time2eat - mama chicken agra agra cantt north_...
3  chokho jeeman marwari jain bhojanalya agra civ...
4  pinch of spice agra civil lines north_indian c...
Successfully loaded and process the dataset (8652, 18)

,Restaurant ID,Restaurant Name,City,Address,Locality,Longitude,Latitude,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Price range,Aggregate rating,Rating text,Votes,Country,Cuisines_processed,Combined_col
0,3400025,Jahanpanah,Agra,"E 23, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra Cantt,78.011544,27.161661,"[North_Indian, Mughlai]",850,No,No,3,3.9,Good,140,India,North_Indian Mughlai,jahanpanah agra agra cantt north_indian mughlai
1,3400341,Rangrezz Restaurant,Agra,"E-20, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra Cantt,0.000000,0.000000,"[North_Indian, Mughlai]",700,No,No,2,3.5,Good,71,India,North_Indian Mughlai,rangrezz restaurant agra agra cantt north_indi...
2,3400005,Time2Eat - Mama Chicken,Agra,"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra Cantt,78.011608,27.160832,[North_Indian],500,No,No,2,3.6,Good,94,India,North_Indian,time2eat - mama chicken agra agra cantt north_...
3,3400021,Chokho Jeeman Marwari Jain Bhojanalya,Agra,"1/48, Delhi Gate, Station Road, Raja Mandi, Ci...",Civil Lines,77.998092,27.195928,[Rajasthani],400,No,No,2,4.0,Very Good,87,India,Rajasthani,chokho jeeman marwari jain bhojanalya agra civ...
4,3400017,Pinch Of Spice,Agra,"23/453, Opposite Sanjay Cinema, Wazipura Road,...",Civil Lines,78.007553,27.201725,"[North_Indian, Chinese, Mughlai]",1000,No,No,3,4.2,Very Good,177,India,North_Indian Chinese Mughlai,pinch of spice agra civil lines north_indian c...

In [37]:
obj.model_develop()
obj.recommendation_by_cuisines(
    prefered_cuisine='Chinese',
    n_recommendation=5,
    min_rating=None,
    city='New Delhi'
)

model successfully build.
No Restaurants are available

Empty DataFrame
Columns: []
Index: []

In [41]:
df=pd.read_csv(os.path.join(path,"final_dataset.csv")).reset_index(drop=True)
df.head()

,Unnamed: 0,Restaurant ID,Restaurant Name,City,Address,Locality,Longitude,Latitude,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Price range,Aggregate rating,Rating text,Votes,Country
0,624,3400025,Jahanpanah,Agra,"E 23, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra Cantt,78.011544,27.161661,"North Indian, Mughlai",850,No,No,3,3.9,Good,140,India
1,625,3400341,Rangrezz Restaurant,Agra,"E-20, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra Cantt,0.000000,0.000000,"North Indian, Mughlai",700,No,No,2,3.5,Good,71,India
2,626,3400005,Time2Eat - Mama Chicken,Agra,"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra Cantt,78.011608,27.160832,North Indian,500,No,No,2,3.6,Good,94,India
3,627,3400021,Chokho Jeeman Marwari Jain Bhojanalya,Agra,"1/48, Delhi Gate, Station Road, Raja Mandi, Ci...",Civil Lines,77.998092,27.195928,Rajasthani,400,No,No,2,4.0,Very Good,87,India
4,628,3400017,Pinch Of Spice,Agra,"23/453, Opposite Sanjay Cinema, Wazipura Road,...",Civil Lines,78.007553,27.201725,"North Indian, Chinese, Mughlai",1000,No,No,3,4.2,Very Good,177,India